name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build Next.js
      run: npm run build

    - name: Upload via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACDCLsOvnIugH6AXyHiLrdqKAUsNrSue8ZZcE+pYWNdHdAAAAKDkiBbP5IgWzwAAAAtzc2gtZWQyNTUxOQAAACDCLsOvnIugH6AXyHiLrdqKAUsNrSue8ZZcE+pYWNdHdAAAAEDxzOEaQisaZc7ZO2slkbZNUnQ0MBbui3GiVc1g5U2VF8Iuw6+ci6AfoBfIeIut2ooBSw2tK57xllwT6lhY10d0AAAAGG5hemltdWRoZWVuMjY3QGdtYWlsLmNvbQECAwQF"
        source: ".next,package.json,public"
        target: "/home/youruser/nextapp"

    - name: SSH Restart Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACDCLsOvnIugH6AXyHiLrdqKAUsNrSue8ZZcE+pYWNdHdAAAAKDkiBbP5IgWzwAAAAtzc2gtZWQyNTUxOQAAACDCLsOvnIugH6AXyHiLrdqKAUsNrSue8ZZcE+pYWNdHdAAAAEDxzOEaQisaZc7ZO2slkbZNUnQ0MBbui3GiVc1g5U2VF8Iuw6+ci6AfoBfIeIut2ooBSw2tK57xllwT6lhY10d0AAAAGG5hemltdWRoZWVuMjY3QGdtYWlsLmNvbQECAwQF"
        script: |
          cd /home/youruser/nextapp
          npm install --omit=dev
          pm2 restart next-app || pm2 start npm --name "next-app" -- start
