name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build Next.js
      run: npm run build

    - name: Start SSH Agent
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Copy files to server
      run: |
        scp -o StrictHostKeyChecking=no -r .next public package.json ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/deployer/food-delivery-admin
    - name: who am i 
      run: whoami
    - name: Restart app on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /home/deployer/food-delivery-admin
          /home/deployer/.nvm/versions/node/v22.16.0/bin/npm install --omit=dev
          /home/deployer/.nvm/versions/node/v22.16.0/bin/pm2 restart next-app
        EOF
